nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']  # Autoriser toutes les origines (à des fins de démonstration uniquement, ne faites pas cela en production sans raisons spécifiques)
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null

