# config/packages/security.yaml
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
            app_user_provider:
                entity:
                    class: App\Entity\User
                    property: telephone
    firewalls:
        login:
            pattern: ^/api/v1/connexion
            stateless: true
            json_login:
                check_path: /api/v1/connexion
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                provider: app_user_provider
            # activate different ways to authenticate
            # switch_user: true
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
            - { path: ^/api/doc, roles: PUBLIC_ACCESS }
            - { path: ^/api/v1/connexion, roles: PUBLIC_ACCESS }
            - { path: ^/api/v1/caisse-partenaire/, roles: PUBLIC_ACCESS }
            - { path: ^/api/v1/caisse/*,       roles: PUBLIC_ACCESS }
            - { path: ^/debug/generateBoxNumber,       roles: PUBLIC_ACCESS }
            # - { path: '^/api/v1/*', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }

